name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint  # Install pylint

    # Run pylint
    - name: Run pylint
      run: |
        pylint tkinterApp.py

    # Run tests
    - name: Run tests
      run: |
        python -m unittest discover tests

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build the application
    - name: Build application
      run: |
        echo "Building application..."
        # Add build steps if needed (e.g., packaging)

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Deploy the application
    - name: Deploy application
      run: |
        echo "Deploying application..."
        # Add deployment steps (e.g., upload to a server or cloud)